#!/usr/bin/env ruby
# This command will automatically be run when you run "rails" with Rails 3 gems installed from the root of your application.

# let's make webrick work with http

require 'rubygems'
require 'rails/commands/server'
require 'rack'
require 'webrick'
require 'webrick/https'

module Rails
  class Server < ::Rack::Server
    def default_options
      super.merge({
          :Port => 3443,
          :environment => (ENV['RAILS_ENV'] || "development").dup,
          :daemonize => false,
          :debugger => false,
          :pid => File.expand_path("tmp/pids/server.pid"),
          :config => File.expand_path("config.ru"),
          :SSLEnable => true,
          :SSLVerifyClient => OpenSSL::SSL::VERIFY_PEER,
          :SSLPrivateKey => OpenSSL::PKey::RSA.new(
                 File.open("certs/server.key").read),
          :SSLCertificate => OpenSSL::X509::Certificate.new(
                 File.open("certs/server.pem").read),
          :SSLCACertificateFile => 'certs/ca/retsyn-ca.pem',
          :SSLCertName => [["CN", WEBrick::Utils::getservername]]
      })
    end
  end
end


APP_PATH = File.expand_path('../../config/application',  __FILE__)
require File.expand_path('../../config/boot',  __FILE__)
require 'rails/commands'

